// Seed segment library — 27 named segments across 4 behavioral/needs-based
// lenses. Consumed by Step 6 Persona Lab (Increment 4). Authored now.
//
// FAIRNESS: every segment is behavioral, needs-based, or financial-profile
// based — never a protected class or close proxy (Reg B / ECOA).

import type { Segment } from '@/types'

export const SEED_SEGMENTS: Segment[] = [
  // ── Value & Rewards Orientation ────────────────────────────────────────────
  {
    id: 'seg_value_maximizer',
    name: 'Rewards Maximizers',
    lens: 'Value & Rewards Orientation',
    description: 'Optimize every purchase for points/cash back; track categories closely.',
    motivations: ['Earn the most rewards', 'Beat the system', 'No annual fee waste'],
    objections: ['Caps and category limits', 'Redemption friction'],
  },
  {
    id: 'seg_value_simplicity',
    name: 'Simplicity Seekers',
    lens: 'Value & Rewards Orientation',
    description: 'Want flat, easy rewards with no categories to manage.',
    motivations: ['One simple rate', 'No tracking', 'Set-and-forget'],
    objections: ['Anything that feels complicated'],
  },
  {
    id: 'seg_value_travel',
    name: 'Aspirational Travelers',
    lens: 'Value & Rewards Orientation',
    description: 'Save toward trips; value miles and no foreign transaction fees.',
    motivations: ['Free/discounted travel', 'Travel perks'],
    objections: ['Blackout dates', 'Complex redemption'],
  },
  {
    id: 'seg_value_cashback',
    name: 'Everyday Cash-Back Users',
    lens: 'Value & Rewards Orientation',
    description: 'Prefer tangible cash back on routine spend.',
    motivations: ['Money back in pocket', 'Predictability'],
    objections: ['Points that feel abstract'],
  },
  {
    id: 'seg_value_fee_averse',
    name: 'Fee-Averse Pragmatists',
    lens: 'Value & Rewards Orientation',
    description: 'Will not pay annual fees; hyper-sensitive to hidden costs.',
    motivations: ['No fees', 'Transparency'],
    objections: ['Annual fees', 'Surprise charges'],
  },
  {
    id: 'seg_value_premium',
    name: 'Premium Perk Seekers',
    lens: 'Value & Rewards Orientation',
    description: 'Will pay for lounge access and elevated benefits if value is clear.',
    motivations: ['Status', 'Premium experiences'],
    objections: ['Perks they won’t use'],
  },
  {
    id: 'seg_value_skeptic',
    name: 'Rewards Skeptics',
    lens: 'Value & Rewards Orientation',
    description: 'Doubt rewards are worth it; suspect a catch.',
    motivations: ['Avoid being upsold'],
    objections: ['"Too good to be true"', 'Fine print'],
  },

  // ── Credit Lifecycle Stage ─────────────────────────────────────────────────
  {
    id: 'seg_credit_newcomer',
    name: 'Credit Newcomers',
    lens: 'Credit Lifecycle Stage',
    description: 'Little/no credit history; getting started.',
    motivations: ['Build credit', 'Get approved'],
    objections: ['Fear of rejection', 'Confusing terms'],
  },
  {
    id: 'seg_credit_builder',
    name: 'Credit Builders',
    lens: 'Credit Lifecycle Stage',
    description: 'Actively improving a fair score.',
    motivations: ['Raise score', 'Qualify for better products'],
    objections: ['Slow progress', 'Unclear what helps'],
  },
  {
    id: 'seg_credit_rebuilder',
    name: 'Credit Rebuilders',
    lens: 'Credit Lifecycle Stage',
    description: 'Recovering after setbacks; rebuilding trust.',
    motivations: ['Second chance', 'Stability'],
    objections: ['Feeling judged', 'High rates'],
  },
  {
    id: 'seg_credit_established',
    name: 'Established Prime',
    lens: 'Credit Lifecycle Stage',
    description: 'Strong score; courted by many issuers.',
    motivations: ['Best terms', 'Premium rewards'],
    objections: ['Switching hassle', 'Loyalty inertia'],
  },
  {
    id: 'seg_credit_optimizer',
    name: 'Score Optimizers',
    lens: 'Credit Lifecycle Stage',
    description: 'Monitor score obsessively; manage utilization.',
    motivations: ['Perfect score', 'Data and tools'],
    objections: ['Hard inquiries', 'Opaque scoring'],
  },
  {
    id: 'seg_credit_thin',
    name: 'Thin-File Returners',
    lens: 'Credit Lifecycle Stage',
    description: 'Past credit gone dormant; re-entering.',
    motivations: ['Re-establish access'],
    objections: ['Starting over feeling'],
  },

  // ── Life Stage ──────────────────────────────────────────────────────────────
  {
    id: 'seg_life_student',
    name: 'Students & Early Career',
    lens: 'Life Stage',
    description: 'New to financial independence.',
    motivations: ['Build habits', 'Affordability'],
    objections: ['Low income', 'Overwhelm'],
  },
  {
    id: 'seg_life_young_family',
    name: 'Young Families',
    lens: 'Life Stage',
    description: 'Growing households balancing spend and saving.',
    motivations: ['Stretch the budget', 'Security'],
    objections: ['Time-poor', 'Risk-averse'],
  },
  {
    id: 'seg_life_established_family',
    name: 'Established Families',
    lens: 'Life Stage',
    description: 'Peak-spend households; multiple goals.',
    motivations: ['Maximize value', 'Plan ahead'],
    objections: ['Complexity', 'Trust'],
  },
  {
    id: 'seg_life_empty_nester',
    name: 'Empty Nesters',
    lens: 'Life Stage',
    description: 'Shifting toward saving and travel.',
    motivations: ['Travel', 'Simplify finances'],
    objections: ['Change fatigue'],
  },
  {
    id: 'seg_life_pre_retiree',
    name: 'Pre-Retirees',
    lens: 'Life Stage',
    description: 'Focused on stability and preservation.',
    motivations: ['Safety', 'Predictable returns'],
    objections: ['Risk', 'Fees'],
  },
  {
    id: 'seg_life_newly_independent',
    name: 'Newly Independent',
    lens: 'Life Stage',
    description: 'First solo accounts after a shared/family setup.',
    motivations: ['Control', 'Confidence'],
    objections: ['Inexperience'],
  },
  {
    id: 'seg_life_small_biz',
    name: 'Small Business Owners',
    lens: 'Life Stage',
    description: 'Separating and managing business cash flow.',
    motivations: ['Cash flow', 'Expense tracking'],
    objections: ['Mixing finances', 'Time'],
  },

  // ── Financial Mindset & Behavior ────────────────────────────────────────────
  {
    id: 'seg_mind_planner',
    name: 'Methodical Planners',
    lens: 'Financial Mindset & Behavior',
    description: 'Budget, automate, and plan deliberately.',
    motivations: ['Control', 'Tools and data'],
    objections: ['Anything impulsive'],
  },
  {
    id: 'seg_mind_optimizer',
    name: 'Debt-Conscious Optimizers',
    lens: 'Financial Mindset & Behavior',
    description: 'Focused on paying down and consolidating debt efficiently.',
    motivations: ['Lower interest', 'Debt-free date'],
    objections: ['Fees that offset savings', 'Hidden terms'],
  },
  {
    id: 'seg_mind_anxious',
    name: 'Financially Anxious',
    lens: 'Financial Mindset & Behavior',
    description: 'Stressed about money; seek reassurance and safety.',
    motivations: ['Peace of mind', 'No surprises'],
    objections: ['Jargon', 'Risk', 'Pressure'],
  },
  {
    id: 'seg_mind_spontaneous',
    name: 'Spontaneous Spenders',
    lens: 'Financial Mindset & Behavior',
    description: 'Live in the moment; rewards and ease drive choices.',
    motivations: ['Instant value', 'Convenience'],
    objections: ['Friction', 'Lecturing tone'],
  },
  {
    id: 'seg_mind_diy',
    name: 'DIY Researchers',
    lens: 'Financial Mindset & Behavior',
    description: 'Read reviews and fine print before deciding.',
    motivations: ['Best informed choice', 'Transparency'],
    objections: ['Vague claims', 'Marketing fluff'],
  },
  {
    id: 'seg_mind_loyal',
    name: 'Brand-Loyal Relationship Bankers',
    lens: 'Financial Mindset & Behavior',
    description: 'Prefer to consolidate with one trusted provider.',
    motivations: ['Trust', 'Simplicity', 'Service'],
    objections: ['Feeling taken for granted'],
  },
]
