// Seed topic backlog — 14 ranked content opportunities for the default brand.
// Consumed by Step 1 Topic Intelligence (Increment 2); authored now so Step 1
// opens full. Synthetic / illustrative.

import type { TopicOpportunity } from '@/types'

export const SEED_TOPIC_BACKLOG: TopicOpportunity[] = [
  {
    id: 'topic_bt_guide',
    title: 'Balance transfer 101: how to move debt the smart way',
    rationale: 'High search demand around debt consolidation entering H2; strong product tie-in.',
    audienceSegment: 'Debt-Conscious Optimizers',
    funnelStage: 'consideration',
    format: 'blog',
    demand: 'High',
    demandScore: 92,
    difficulty: 'Medium',
    complianceSensitivity: 'High',
    onBrand: true,
    tags: ['balance-transfer', 'apr', 'debt'],
  },
  {
    id: 'topic_creditwise_explainer',
    title: 'What your credit score really means (and how to improve it)',
    rationale: 'Evergreen demand; reinforces CreditWise and the "you’re in control" message.',
    audienceSegment: 'Credit Builders',
    funnelStage: 'awareness',
    format: 'explainer',
    demand: 'High',
    demandScore: 88,
    difficulty: 'Low',
    complianceSensitivity: 'Medium',
    onBrand: true,
    tags: ['credit-score', 'education'],
  },
  {
    id: 'topic_travel_rewards',
    title: 'How to maximize travel rewards for summer trips',
    rationale: 'Seasonal travel peak; aligns with Venture proof points.',
    audienceSegment: 'Aspirational Travelers',
    funnelStage: 'consideration',
    format: 'blog',
    demand: 'High',
    demandScore: 84,
    difficulty: 'Medium',
    complianceSensitivity: 'Medium',
    onBrand: true,
    tags: ['rewards', 'travel'],
  },
  {
    id: 'topic_no_fee_explainer',
    title: 'The real cost of hidden bank fees — and how to avoid them',
    rationale: 'Differentiates on the "no hidden fees" value prop; competitive gap.',
    audienceSegment: 'Value Seekers',
    funnelStage: 'awareness',
    format: 'blog',
    demand: 'Medium',
    demandScore: 71,
    difficulty: 'Low',
    complianceSensitivity: 'Low',
    onBrand: true,
    tags: ['fees', 'savings'],
  },
  {
    id: 'topic_back_to_school',
    title: 'Smart back-to-school spending without the stress',
    rationale: 'Seasonal (Aug); everyday spend + cash-back angle.',
    audienceSegment: 'Budgeting Families',
    funnelStage: 'awareness',
    format: 'email',
    demand: 'Medium',
    demandScore: 68,
    difficulty: 'Low',
    complianceSensitivity: 'Low',
    onBrand: true,
    tags: ['seasonal', 'rewards'],
  },
  {
    id: 'topic_first_card',
    title: 'Choosing your first credit card: a beginner’s guide',
    rationale: 'Strong consideration demand from credit newcomers; lifecycle entry point.',
    audienceSegment: 'Credit Newcomers',
    funnelStage: 'consideration',
    format: 'explainer',
    demand: 'High',
    demandScore: 80,
    difficulty: 'Medium',
    complianceSensitivity: 'Medium',
    onBrand: true,
    tags: ['credit-score', 'education'],
  },
  {
    id: 'topic_savings_rate',
    title: 'How high-yield savings actually works',
    rationale: 'Rate-curiosity demand; supports 360 Performance Savings.',
    audienceSegment: 'Savers',
    funnelStage: 'consideration',
    format: 'explainer',
    demand: 'Medium',
    demandScore: 66,
    difficulty: 'Medium',
    complianceSensitivity: 'Medium',
    onBrand: true,
    tags: ['savings', 'apr'],
  },
  {
    id: 'topic_holiday_spend',
    title: 'A no-regret holiday spending plan',
    rationale: 'Q4 seasonal; budgeting + rewards angle.',
    audienceSegment: 'Budgeting Families',
    funnelStage: 'awareness',
    format: 'blog',
    demand: 'Medium',
    demandScore: 64,
    difficulty: 'Low',
    complianceSensitivity: 'Low',
    onBrand: true,
    tags: ['seasonal', 'budgeting'],
  },
  {
    id: 'topic_tax_season',
    title: 'Tax season money moves to make now',
    rationale: 'Q1 seasonal spike; practical, shareable.',
    audienceSegment: 'Financially Engaged',
    funnelStage: 'awareness',
    format: 'blog',
    demand: 'Medium',
    demandScore: 62,
    difficulty: 'Medium',
    complianceSensitivity: 'Low',
    onBrand: true,
    tags: ['seasonal', 'education'],
  },
  {
    id: 'topic_apr_explainer',
    title: 'APR explained in plain English',
    rationale: 'High question demand; reinforces transparency. Heavy disclosure load.',
    audienceSegment: 'Credit Builders',
    funnelStage: 'awareness',
    format: 'explainer',
    demand: 'High',
    demandScore: 78,
    difficulty: 'Low',
    complianceSensitivity: 'High',
    onBrand: true,
    tags: ['apr', 'education'],
  },
  {
    id: 'topic_fraud_protection',
    title: 'How to spot and stop card fraud fast',
    rationale: 'Trust-building; supports 24/7 monitoring proof point.',
    audienceSegment: 'Security-Minded',
    funnelStage: 'consideration',
    format: 'blog',
    demand: 'Medium',
    demandScore: 60,
    difficulty: 'Low',
    complianceSensitivity: 'Low',
    onBrand: true,
    tags: ['security', 'trust'],
  },
  {
    id: 'topic_small_business',
    title: 'Cash flow tips for new small businesses',
    rationale: 'Adjacent Spark Business audience; content-gap opportunity.',
    audienceSegment: 'Small Business Owners',
    funnelStage: 'consideration',
    format: 'blog',
    demand: 'Medium',
    demandScore: 58,
    difficulty: 'Medium',
    complianceSensitivity: 'Medium',
    onBrand: true,
    tags: ['business', 'education'],
  },
  {
    id: 'topic_debt_payoff',
    title: 'Debt payoff: snowball vs. avalanche',
    rationale: 'High demand; pairs with balance-transfer consideration.',
    audienceSegment: 'Debt-Conscious Optimizers',
    funnelStage: 'consideration',
    format: 'explainer',
    demand: 'High',
    demandScore: 76,
    difficulty: 'Medium',
    complianceSensitivity: 'Medium',
    onBrand: true,
    tags: ['debt', 'budgeting'],
  },
  {
    id: 'topic_crypto_offbrand',
    title: 'Should you buy crypto with a credit card?',
    rationale: 'Trending search interest, but conflicts with the brand’s responsible-credit positioning and carries elevated risk.',
    audienceSegment: 'Trend Chasers',
    funnelStage: 'awareness',
    format: 'blog',
    demand: 'High',
    demandScore: 83,
    difficulty: 'High',
    complianceSensitivity: 'High',
    onBrand: false,
    offBrandReason:
      'Encouraging credit-funded crypto speculation conflicts with the brand’s responsible-credit, "you’re in control" positioning and raises UDAAP/suitability concerns.',
    tags: ['crypto', 'risk'],
  },
]
